const API_URL = 'YOUR_API_URL_HERE';
const GITHUB_CLIENT_ID = 'YOUR_GITHUB_CLIENT_ID';
const GITHUB_CLIENT_SECRET = 'YOUR_GITHUB_CLIENT_SECRET';

export { API_URL, GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET };